.TH CGOMOKU 6 "Version 1, Release 4" "W Window System" "W PROGRAMS"
.SH NAME
cgomoku \- Gomoku board game client for console
.SH SYNOPSIS
.nf
cgomoku [-c \fIaddress\fP]
.fi
.SH DESCRIPTION
\fICGomoku\fP is a curses version of Gomoku board game clients for
the networked turn based, two player game framework by Eero Tamminen.
.SH STARTING GAME
Before starting a game one has to contact another game client.  This
happens either by setting up a server and accepting a connection or by
connecting yourself to another game server.
.PP
With curses version one needs to use '-c' option to specify the address
into which to connect (e.g.  'creversi -c saturn.outer.space.org').  If
this option isn't used, the game will itself setup a server.
.PP
After connecting another player, you can start the game and begin to
play.  Note that continuing (for clients that support board editing
before play) asks confirmation from the other player before proceeding.
.SH GOMOKU RULES
Players position a stone at the time and the game is won by the person
who first gets five of his/her stones onto a row, either horizontally,
vertically or diagonally.
.PP
It's proven that the starter can always win the game, but with amateur
players that's not an issue (mainly concerns players on inter/national
level, who will play the Pente/Renju variant which sets some limitations
to the starting player).
.SH SEE ALSO
.IR wgomoku (6),
.IR cgo (6),
.IR cpente (6)
.SH LAST CHANGED
09/2009 by Eero Tamminen
