.TH WLIFE 6 "Version 1, Release 4" "W Window System" "W PROGRAMS"
.SH NAME
wlife \- Conway's game of life for W
.SH SYNOPSIS
wlife [-g \fIgeometry\fP]
.SH DESCRIPTION
.I Wlife
is a small program which serves two purposes: first it calculates and draws a
two-dimensional cellular automaton and second it shows you how to deal with
buttons and events.
.PP
You can set pixels by pressing the left mouse button and clear them with the
right one, if the simulation isn't actually running.
.PP
It now takes a geometry argument to work on variable fields. The positioning
part of geometry is not yet implemented.
.SH BUGS
xlife is faster...
.SH SEE ALSO
scan_geometry(3)
.SH LAST CHANGED
15th. Feb. 1996 by TeSche
