.TH WSOLITAIRE 6 "Version 1, Release 4" "W Window System" "W PROGRAMS"
.SH NAME
wsolitaire \- classic Solitaire board game for W
.SH SYNOPSIS
wsolitaire [-u]
.SH DESCRIPTION
.I Wsolitaire
is a one player board game.  The board consists of pieces and 'holes' in
which the pieces are.  At the beginning only the hole in the middle is empty.
You can remove piece from the board by 'jumping' over it with another piece
(to an empty hole). Your mission is to remove all the pieces from the board
except the last one, which you should try to get into the middle hole at the
end.
.PP
You can undo the last move with the right mouse button. By using the '-u'
command line option, you'll have unlimited UNDOs. However, that's
cheating...
.PP
You can exit the program at the middle of a game with the 'q' key.
.SH LAST CHANGED
12/1995 by Eero Tamminen
