/*
 * declarations for the Wlib and Wt wrapper initialization functions
 * generated by tolua.
 */
extern int tolua_wlib_open (lua_State* tolua_S);
extern void tolua_wlib_close (lua_State* tolua_S);
extern int tolua_wt_open (lua_State* tolua_S);
extern void tolua_wt_close (lua_State* tolua_S);
