.TH STARTW 1 "Version 1, Release 4" "W Window System" "W PROGRAMS"
.SH NAME
startw \- script to start the W Window System server
.SH SYNOPSIS
startw
.SH DESCRIPTION
.I startw
undefines LANG as W terminals don't support now prelevant UTF-8 encoding
and directs the W server error messages to user's home directory when
starting the server.
.SH SEE ALSO
.IR wserver (1)
.SH LAST CHANGED
30th Aug 2009 by Eero Tamminen
