.TH WCHAT 1 "Version 1, Release 4" "W Window System" "W PROGRAMS"
.SH NAME
wchat \- simple client/server chat program for W
.SH SYNOPSIS
wchat [\foptions\fP]
.SH DESCRIPTION
\fIWchat\fP is a simple chat program for W with which two persons can
communication over the network.
.SH OPTIONS
.TP
\fI-l\fP \fIlines\fP
.TP
\fI-c\fP \fIcolumns\fP
.TP
\fI-b\fP \fIbuffered lines\fP
.SH SEE ALSO
.IR ring(1)
.SH LAST CHANGED
09/2009 by Eero Tamminen
