.TH WCPYRGT 1 "Version 1, Release 4" "W Window System" "W PROGRAMS"
.SH NAME
wcpyrgt \- show graphical W copyright notice
.SH SYNOPSIS
.nf
wcpyrgt
.fi
.SH DESCRIPTION
.I Wcpyrgt
shows a graphics W Window System welcome and copyright notice.
It's automatically started by the W server.
.SH SEE ALSO
.IR wserver (1),
.IR startw (1)
.SH LAST CHANGED
09/2009 by Eero Tamminen
