.TH WANT 1 "Version 1, Release 4" "W Window System" "W PROGRAMS"
.SH NAME
wengine \- another performance monitor for W
.SH SYNOPSIS
.B "wengine"
.SH DESCRIPTION
.I Wengine
displays a combustion engine at work and the number of rounds
per minute (RPM) it reaches. This RPM value can be seen as an overall
performance value for the version of W and the machine you are running
.I wengine
on.
.sp
Here are some RPM values for different machines:
.TP
ST, 68000 @ 8MHz, no FPU, mono driver:
14 RPM
.TP
STonX ST emulator @ 10Mhz, mono driver:
36 RPM
.TP
TT, 68030 @ 33MHz, mono driver:
130 RPM
.TP
Sun Sparc2, direct8 driver:
430 RPM
.TP
Amiga NetBSD, 68060 @ 50Mhz, direct8 / 1152x900:
687 RPM
.TP
x86-Linux, Pentium @ 133MHz, W2Xlib emulation:
1260 RPM
.TP
x86-Linux, Pentium @ 133MHz, bmono / 640x480:
1950 RPM
.TP
x86-Linux, Pentium @ 133MHz, direct8 / 320x200:
2300 RPM
.TP
x86-Linux, AMD XP @ 1GHz, direct8 / 800x600 in SDL window on 16-bit X11
16000 RPM
.SH AUTHOR
Kay Roemer <roemer@informatik.uni-frankfurt.de>
.SH SEE ALSO
Anything on W.
.SH LAST CHANGED
11/97 by Eero Tamminen
