.TH WEYES 1 "Version 1, Release 4" "W Window System" "W PROGRAMS"
.SH NAME
weyes \- eyes that follow mouse (xeyes for W)
.SH SYNOPSIS
weyes [-h] [-r] [-g \fIgeometry\fP]
.SH DESCRIPTION
.I Weyes
opens a window with two eyes which will always look at the mouse, so if you
should once have lost it in the pixel chaos on your screen... :)
.PP
Weyes supports the \fIgeometry\fP command line option, for details on
how to use that take a look at the appropriate manpage.
.PP
Use the \fI-r\fP option to put \fIweyes\fP onto root window (my favorite).
This way W server doesn't need to allocate window bitmap for it.
.SH SEE ALSO
scan_geometry(3)
.SH LAST CHANGED
30th. Nov. 1997 by Eero Tamminen
