.TH WFONT 1 "Version 1, Release 4" "W Window System" "W PROGRAMS"
.SH NAME
wfont \- show given W font
.SH SYNOPSIS
.nf
wfont <font-1 filename> [<font-2 filename> ...]
.fi
.SH DESCRIPTION
.I Wfont
showing the given font(s) in windows.  It decomposes the font file name
into a W font request, loads the font and the shows it in several server
generated style combinations.  It can be used for example testing the
readability of style effects on font before modifying the font header.
.SH AUTHOR
(w) 11/1996 by Eero Tamminen
