.TH WFONTDEMO 1 "Version 1, Release 4" "W Window System" "W PROGRAMS"
.SH NAME
wfontdemo \- display all available W fonts
.SH SYNOPSIS
wfontdemo <W font directory>
.SH DESCRIPTION
.I Wfontdemo
prints a short string in all available fonts, in all available styles,
scrolling the window if necessary.
.PP
Note that due to directory sorting done by `ls' the fonts may not appear
in the order you might expect them.
.SH BUGS
can't change font dir
.SH LAST CHANGED
15th. Feb. 1996 by TeSche
