.TH WSETBG 1 "Version 1, Release 4" "W Window System" "W PROGRAMS"
.SH NAME
wsetbg \- set W server root window background
.SH SYNOPSIS
wsetbg
.br
wsetbg <\fIpattern id\fP>
.br
wsetbg <\fIhatch id\fP> <\fIline width\fP> <\fItimes\fP>
.br
wsetbg <\fIshared color index\fP>
.br
wsetbg <\fIred\fP> <\fIgreen\fP> <\fIblue\fP>
.SH DESCRIPTION
.I Wsetbg
is a tool for changing the background color or pattern of the W root
(background) window.  If you won't give it any arguments, it will set
the default background pattern and color.  The \fIpattern id\fP should
be in hexadecimals, \fIhatch parameters\fP according to \fIw_hatch\fP(3)
arguments, \fIshared color index\fP smaller than number of shared colors
on server (or the value is interpreted as pattern id) and \fIcolor
component values\fP should be between 0-255.
.SH NOTES
If you'll specify the root window color values, you won't see the
correct ones until you'll move the mouse pointer on root window area.
Same applies for shared colors too if the window where your mouse is has
re-defined them for itself.
.SH SEE ALSO
.IR w_setpattern (3),
.IR w_hatch (3)
and 
.IR Wlib.h
.SH LAST CHANGED
27th. Feb. 1997 by Eero Tamminen
