.TH WVIEW 1 "Version 1, Release 4" "W Window System" "W PROGRAMS"
.SH NAME
wview \- view images on W
.SH SYNOPSIS
wview [images]
.SH DESCRIPTION
.I wview
show JPEG, PNG, GIF etc. images on the W window system using \fIdjpeg\fP,
\fInetpbm\fP utilities and \fIwbm\fP.
.SH SEE ALSO
.IR wbm (1),
.IR djpeg (1),
.IR pnmquant (1),
.IR pnmdepth (1),
.IR pngtopnm (1),
.IR giftopnm (1),
.IR anytopnm (1)
.SH LAST CHANGED
09/2009 by Eero Tamminen
