.TH WVT 1 "Version 1, Release 4" "W Window System" "W PROGRAMS"
.SH NAME
wvt \- more advanced terminal emulator for W
.SH SYNOPSIS
wvt [options]
.SH DESCRIPTION
.I wvt
is a more advanced version of the \fIwterm\fP terminal emulator.  In
addition to \fIwterm\fP features, it supports copy & paste and has
scrollback buffer / history. It's implemented using the W toolkit
terminal widget.
.SH SEE ALSO
For more information on the W terminal features, see:
.IR wterm (1)
.SH LAST CHANGED
09/2009 by Eero Tamminen
