#
# Makefile for the generic W graphics routines
#

include ../../../.config

CFLAGS = $(BASECFLAGS) $(SERVERCFLAGS)

OBJS = generic_polygon.o generic_bezier.o generic_circle.o generic_box.o

all: $(OBJS)
